name: ‚è≥ WakaTime Stats

on:
  workflow_call:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'üìÇ Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'üõ†Ô∏è Update WakaTime Stats'
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          SHOW_LINES_OF_CODE: true
          COMMIT_MESSAGE: 'chore: update wakatime stats ‚è≥'
