name: 'ğŸ§Š Generate 3D Contribution Grap'

on:
  schedule:
    # æ¯æ—¥ 15:00 UTC (æ—¥æœ¬æ™‚é–“ 00:00) ã«è‡ªå‹•å®Ÿè¡Œ
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    name: 'Run 3D Contrib Process'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 'ğŸ“‚ Checkout Repository'
        uses: actions/checkout@v4

      - name: 'ğŸ› ï¸ Build 3D Graph'
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: 'ğŸšš Move Output to Directory'
        run: |
          mkdir -p image/3d-contrib
          cp -r profile-3d-contrib/* image/3d-contrib/

      - name: 'ğŸš€ Commit and Push Updates'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add image/3d-contrib/*
          if ! git diff --cached --quiet; then
            git commit -m "chore: update 3d contribution graph âœ¨"
            git push origin main
          fi
