name: Update Github Activity

on:
  schedule:
    # æ—¥æœ¬æ™‚é–“ 00:00 (UTC 15:00)
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: update-activity-readme
    runs-on: ubuntu-latest
    timeout-minutes: 5

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Update Activity
    uses: jamesgeorge007/github-activity-readme@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      MAX_LINES: 10
      COMMIT_MSG: "ğŸ“ Committed to"
      ISSUE_MSG: "â—ï¸ Opened issue in"
      PR_MSG: "ğŸ Opened PR in"
      FOLLOW_MSG: "ğŸƒ Started following"