name: WakaTime Stats

on:
  schedule:
    # 日本時間 00:00 (UTC 15:00)
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: update-wakatime-stats
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          SHOW_TOTAL_CODE_TIME: false
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          DEBUG_LOGGING: false